name: Testrun test suite

on:
  pull_request:
  schedule:
    - cron: '0 13 * * *'

jobs:
  testrun_baseline:
    name:  Baseline
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout source
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Install dependencies
        shell: bash {0}
        run: cmd/prepare
      - name: Package Testrun
        shell: bash {0}
        run: cmd/package
      - name: Install Testrun
        shell: bash {0}
        timeout-minutes: 10
        run: sudo dpkg -i testrun*.deb
      - name: Run baseline tests
        shell: bash {0}
        run: testing/baseline/test_baseline
    
  testrun_tests:
    name:  Tests
    runs-on: ubuntu-20.04
    needs: testrun_baseline
    timeout-minutes: 45
    steps:
      - name: Checkout source
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Install dependencies
        shell: bash {0}
        run: cmd/prepare
      - name: Package Testrun  
        shell: bash {0}
        run: cmd/package
      - name: Install Testrun
        shell: bash {0}
        run: sudo dpkg -i testrun*.deb
      - name: Run tests
        shell: bash {0}
        run: testing/tests/test_tests
      - name: Archive runtime results
        if: ${{ always() }}
        run: sudo tar --exclude-vcs -czf runtime.tgz /usr/local/testrun/runtime/
      - name: Upload runtime results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: runtime_${{ github.workflow }}_${{ github.run_id }}
          path: runtime.tgz

  testrun_api:
    name:  API
    runs-on: ubuntu-20.04
    timeout-minutes: 40
    steps:
      - name: Checkout source
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Install dependencies
        shell: bash {0}
        run: cmd/prepare
      - name: Package Testrun  
        shell: bash {0}
        run: cmd/package
      - name: Install Testrun
        shell: bash {0}
        run: sudo dpkg -i testrun*.deb
        timeout-minutes: 30
      - name: Run tests
        shell: bash {0}
        run: testing/api/test_api
      - name: Archive runtime results
        if: ${{ always() }}
        run: sudo tar --exclude-vcs -czf runtime.tgz /usr/local/testrun/runtime/ /usr/local/testrun/local/
      - name: Upload runtime results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: runtime_${{ github.workflow }}_${{ github.run_id }}
          path: runtime.tgz

  pylint:
    name:  Pylint
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout source
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Run pylint
        shell: bash {0}
        run: testing/pylint/test_pylint

  testrun_package:
    name: Package
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout source
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Package Testrun
        shell: bash {0}
        run: cmd/package
      - name: Archive package
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: Testrun Installer
          path: testrun*.deb

  testrun_ui:
    name: UI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Install Node
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version: 18.10.0
    - name: Install Chromium Browser
      run: sudo apt install chromium-browser
    - name: Install dependencies
      run: npm install && npm ci
      working-directory: ./modules/ui
    - name: Run tests
      run: |
        export CHROME_BIN=/usr/bin/chromium-browser
        CI=true npm run test-headless
      env:
        CI: true
      working-directory: ./modules/ui
